# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Module2' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Module2
  pod 'MainWorkSpaceDemo/BaseTool', :path => '../MainWorkSpaceDemo.podspec'

  target 'Module2Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Module2UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
